# Generated by Django 3.0.6 on 2020-06-03 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(default=django.utils.timezone.now, max_length=128, unique=True)),
                ('roomId', models.CharField(default='404', max_length=12)),
                ('name', models.CharField(max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['c_time'],
            },
        ),
    ]
