# Generated by Django 3.0.6 on 2020-06-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identity',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
