# Generated by Django 3.0.6 on 2020-06-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200603_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='roomId',
            field=models.CharField(max_length=12),
        ),
    ]
