# Generated by Django 2.2.7 on 2020-06-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200603_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='roomId',
            field=models.CharField(choices=[('309c', '309c'), ('310c', '310c'), ('311c', '311c'), ('312c', '312c'), ('f3', 'f3')], default='309c', max_length=128),
        ),
        migrations.DeleteModel(
            name='room',
        ),
    ]
