# Generated by Django 2.2.7 on 2020-06-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200608_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='roomId',
            field=models.CharField(choices=[('309', '309'), ('310', '310'), ('311', '311'), ('312', '312'), ('313', '313')], default='309c', max_length=128),
        ),
    ]
