# Generated by Django 3.0.6 on 2020-06-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200601_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('administrator', '系统管理员'), ('manager', '酒店经理'), ('templates', '前台'), ('client', '客户')], default='客户', max_length=32),
        ),
    ]
