# Generated by Django 3.0.6 on 2020-06-01 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200601_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='identity',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='roomId',
            field=models.CharField(default='404', max_length=12),
        ),
    ]
