# Generated by Django 3.0.6 on 2020-06-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200601_1421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
