# Generated by Django 3.0.7 on 2020-06-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('administrator', '系统管理员'), ('manager', '酒店经理'), ('reception', '前台'), ('client', '客户')], default='客户', max_length=32),
        ),
    ]
